package cflog2otel_test

import (
	"context"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/mashiike/cflog2otel"
	"github.com/stretchr/testify/require"
)

func ptr[T any](v T) *T {
	return &v
}

func must[T any](v T, err error) T {
	if err != nil {
		panic(err)
	}
	return v
}

func TestParseCloudFrontLog(t *testing.T) {
	expectedLogs := []cflog2otel.CELVariablesLog{
		{
			Type:                   "CloudFront Standard Log",
			Date:                   "2019-12-01",
			Time:                   "22:42:31",
			Timestamp:              must(time.Parse("2006-01-02 15:04:05", "2019-12-01 22:42:31")),
			EdgeLocation:           ptr("LAX1"),
			ScBytes:                ptr(392),
			ClientIP:               ptr("192.0.2.100"),
			CsMethod:               ptr("GET"),
			CsHost:                 ptr("d111111abcdef8.cloudfront.net"),
			CsURIStem:              ptr("/index.html"),
			ScStatus:               ptr(200),
			ScStatusCategory:       ptr("2xx"),
			CsReferer:              nil,
			CsUserAgent:            ptr("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"),
			CsURIQuery:             nil,
			CsCookie:               nil,
			EdgeResultType:         ptr("Hit"),
			EdgeRequestID:          ptr("SOX4xwn4XV6Q4rgb7XiVGOHms_BGlTAC4KyHmureZmBNrjGdRLiNIQ=="),
			HostHeader:             ptr("d111111abcdef8.cloudfront.net"),
			CsProtocol:             ptr("https"),
			CsBytes:                ptr(23),
			TimeTaken:              ptr(0.001),
			XForwardedFor:          nil,
			SslProtocol:            ptr("TLSv1.2"),
			SslCipher:              ptr("ECDHE-RSA-AES128-GCM-SHA256"),
			EdgeResponseResultType: ptr("Hit"),
			CsProtocolVersion:      ptr("HTTP/2.0"),
			FleStatus:              nil,
			FleEncryptedFields:     nil,
			CPort:                  ptr(11040),
			TimeToFirstByte:        ptr(0.001),
			EdgeDetailedResultType: ptr("Hit"),
			ScContentType:          ptr("text/html"),
			ScContentLen:           ptr(78),
			ScRangeStart:           nil,
			ScRangeEnd:             nil,
		},
		{
			Type:                   "CloudFront Standard Log",
			Date:                   "2019-12-01",
			Time:                   "22:42:31",
			Timestamp:              must(time.Parse("2006-01-02 15:04:05", "2019-12-01 22:42:31")),
			EdgeLocation:           ptr("LAX1"),
			ScBytes:                ptr(392),
			ClientIP:               ptr("192.0.2.100"),
			CsMethod:               ptr("GET"),
			CsHost:                 ptr("d111111abcdef8.cloudfront.net"),
			CsURIStem:              ptr("/index.html"),
			ScStatus:               ptr(200),
			ScStatusCategory:       ptr("2xx"),
			CsReferer:              nil,
			CsUserAgent:            ptr("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"),
			CsURIQuery:             nil,
			CsCookie:               nil,
			EdgeResultType:         ptr("Hit"),
			EdgeRequestID:          ptr("k6WGMNkEzR5BEM_SaF47gjtX9zBDO2m349OY2an0QPEaUum1ZOLrow=="),
			HostHeader:             ptr("d111111abcdef8.cloudfront.net"),
			CsProtocol:             ptr("https"),
			CsBytes:                ptr(23),
			TimeTaken:              ptr(0.0),
			XForwardedFor:          nil,
			SslProtocol:            ptr("TLSv1.2"),
			SslCipher:              ptr("ECDHE-RSA-AES128-GCM-SHA256"),
			EdgeResponseResultType: ptr("Hit"),
			CsProtocolVersion:      ptr("HTTP/2.0"),
			FleStatus:              nil,
			FleEncryptedFields:     nil,
			CPort:                  ptr(11040),
			TimeToFirstByte:        ptr(0.0),
			EdgeDetailedResultType: ptr("Hit"),
			ScContentType:          ptr("text/html"),
			ScContentLen:           ptr(78),
			ScRangeStart:           nil,
			ScRangeEnd:             nil,
		},
		{
			Type:                   "CloudFront Standard Log",
			Date:                   "2019-12-01",
			Time:                   "22:42:31",
			Timestamp:              must(time.Parse("2006-01-02 15:04:05", "2019-12-01 22:42:31")),
			EdgeLocation:           ptr("LAX1"),
			ScBytes:                ptr(392),
			ClientIP:               ptr("192.0.2.100"),
			CsMethod:               ptr("GET"),
			CsHost:                 ptr("d111111abcdef8.cloudfront.net"),
			CsURIStem:              ptr("/index.html"),
			ScStatus:               ptr(200),
			ScStatusCategory:       ptr("2xx"),
			CsReferer:              nil,
			CsUserAgent:            ptr("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"),
			CsURIQuery:             nil,
			CsCookie:               nil,
			EdgeResultType:         ptr("Hit"),
			EdgeRequestID:          ptr("f37nTMVvnKvV2ZSvEsivup_c2kZ7VXzYdjC-GUQZ5qNs-89BlWazbw=="),
			HostHeader:             ptr("d111111abcdef8.cloudfront.net"),
			CsProtocol:             ptr("https"),
			CsBytes:                ptr(23),
			TimeTaken:              ptr(0.001),
			XForwardedFor:          nil,
			SslProtocol:            ptr("TLSv1.2"),
			SslCipher:              ptr("ECDHE-RSA-AES128-GCM-SHA256"),
			EdgeResponseResultType: ptr("Hit"),
			CsProtocolVersion:      ptr("HTTP/2.0"),
			FleStatus:              nil,
			FleEncryptedFields:     nil,
			CPort:                  ptr(11040),
			TimeToFirstByte:        ptr(0.001),
			EdgeDetailedResultType: ptr("Hit"),
			ScContentType:          ptr("text/html"),
			ScContentLen:           ptr(78),
			ScRangeStart:           nil,
			ScRangeEnd:             nil,
		},
		{
			Type:                   "CloudFront Standard Log",
			Date:                   "2019-12-01",
			Time:                   "22:51:27",
			Timestamp:              must(time.Parse("2006-01-02 15:04:05", "2019-12-01 22:51:27")),
			EdgeLocation:           ptr("SEA19-C1"),
			ScBytes:                ptr(900),
			ClientIP:               ptr("192.0.2.200"),
			CsMethod:               ptr("GET"),
			CsHost:                 ptr("d111111abcdef8.cloudfront.net"),
			CsURIStem:              ptr("/favicon.ico"),
			ScStatus:               ptr(502),
			ScStatusCategory:       ptr("5xx"),
			CsReferer:              ptr("http://www.example.com/"),
			CsUserAgent:            ptr("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"),
			CsURIQuery:             nil,
			CsCookie:               nil,
			EdgeResultType:         ptr("Error"),
			EdgeRequestID:          ptr("1pkpNfBQ39sYMnjjUQjmH2w1wdJnbHYTbag21o_3OfcQgPzdL2RSSQ=="),
			HostHeader:             ptr("www.example.com"),
			CsProtocol:             ptr("http"),
			CsBytes:                ptr(675),
			TimeTaken:              ptr(0.102),
			XForwardedFor:          nil,
			SslProtocol:            nil,
			SslCipher:              nil,
			EdgeResponseResultType: ptr("Error"),
			CsProtocolVersion:      ptr("HTTP/1.1"),
			FleStatus:              nil,
			FleEncryptedFields:     nil,
			CPort:                  ptr(25260),
			TimeToFirstByte:        ptr(0.102),
			EdgeDetailedResultType: ptr("OriginDnsError"),
			ScContentType:          ptr("text/html"),
			ScContentLen:           ptr(507),
			ScRangeStart:           nil,
			ScRangeEnd:             nil,
		},
		{
			Type:                   "CloudFront Standard Log",
			Date:                   "2019-12-01",
			Time:                   "22:51:26",
			Timestamp:              must(time.Parse("2006-01-02 15:04:05", "2019-12-01 22:51:26")),
			EdgeLocation:           ptr("SEA19-C1"),
			ScBytes:                ptr(900),
			ClientIP:               ptr("192.0.2.200"),
			CsMethod:               ptr("GET"),
			CsHost:                 ptr("d111111abcdef8.cloudfront.net"),
			CsURIStem:              ptr("/"),
			ScStatus:               ptr(502),
			ScStatusCategory:       ptr("5xx"),
			CsReferer:              nil,
			CsUserAgent:            ptr("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"),
			CsURIQuery:             nil,
			CsCookie:               nil,
			EdgeResultType:         ptr("Error"),
			EdgeRequestID:          ptr("3AqrZGCnF_g0-5KOvfA7c9XLcf4YGvMFSeFdIetR1N_2y8jSis8Zxg=="),
			HostHeader:             ptr("www.example.com"),
			CsProtocol:             ptr("http"),
			CsBytes:                ptr(735),
			TimeTaken:              ptr(0.107),
			XForwardedFor:          nil,
			SslProtocol:            nil,
			SslCipher:              nil,
			EdgeResponseResultType: ptr("Error"),
			CsProtocolVersion:      ptr("HTTP/1.1"),
			FleStatus:              nil,
			FleEncryptedFields:     nil,
			CPort:                  ptr(3802),
			TimeToFirstByte:        ptr(0.107),
			EdgeDetailedResultType: ptr("OriginDnsError"),
			ScContentType:          ptr("text/html"),
			ScContentLen:           ptr(507),
			ScRangeStart:           nil,
			ScRangeEnd:             nil,
		},
		{
			Type:                   "CloudFront Standard Log",
			Date:                   "2019-12-01",
			Time:                   "22:51:02",
			Timestamp:              must(time.Parse("2006-01-02 15:04:05", "2019-12-01 22:51:02")),
			EdgeLocation:           ptr("SEA19-C2"),
			ScBytes:                ptr(900),
			ClientIP:               ptr("192.0.2.200"),
			CsMethod:               ptr("GET"),
			CsHost:                 ptr("d111111abcdef8.cloudfront.net"),
			CsURIStem:              ptr("/"),
			ScStatus:               ptr(502),
			ScStatusCategory:       ptr("5xx"),
			CsReferer:              nil,
			CsUserAgent:            ptr("curl/7.55.1"),
			CsURIQuery:             nil,
			CsCookie:               nil,
			EdgeResultType:         ptr("Error"),
			EdgeRequestID:          ptr("kBkDzGnceVtWHqSCqBUqtA_cEs2T3tFUBbnBNkB9El_uVRhHgcZfcw=="),
			HostHeader:             ptr("www.example.com"),
			CsProtocol:             ptr("http"),
			CsBytes:                ptr(387),
			TimeTaken:              ptr(0.103),
			XForwardedFor:          nil,
			SslProtocol:            nil,
			SslCipher:              nil,
			EdgeResponseResultType: ptr("Error"),
			CsProtocolVersion:      ptr("HTTP/1.1"),
			FleStatus:              nil,
			FleEncryptedFields:     nil,
			CPort:                  ptr(12644),
			TimeToFirstByte:        ptr(0.103),
			EdgeDetailedResultType: ptr("OriginDnsError"),
			ScContentType:          ptr("text/html"),
			ScContentLen:           ptr(507),
			ScRangeStart:           nil,
			ScRangeEnd:             nil,
		},
	}
	bs, err := os.ReadFile("testdata/cf_log.txt")
	require.NoError(t, err)
	logs, err := cflog2otel.ParseCloudFrontLog(context.Background(), strings.NewReader(string(bs)))
	require.NoError(t, err)
	require.Len(t, logs, 6)
	for i, expectedLog := range expectedLogs {
		require.EqualValues(t, expectedLog, logs[i], "index: %d", i)
	}
}
